# Generated by Django 3.1.7 on 2021-07-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='customer',
        ),
    ]
