# Generated by Django 3.1.7 on 2021-07-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_auto_20210725_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
